#!/usr/bin/bash

if [[ -e /home/tik/.config/autostart/org.opensuse.tik.desktop ]]; then
  USERNAME="tik"
  SESSION_DESKTOP="/usr/share/wayland-sessions/gnome-wayland.desktop"
else
  USERNAME="$(getent passwd 1000 | cut -d: -f1)"
  if [[ -n "$USERNAME" ]]; then
    SESSION_DESKTOP="/usr/share/wayland-sessions/gamescope-session-steam.desktop"
  else
    USERNAME="root"
    SESSION_DESKTOP="/usr/share/wayland-sessions/gnome-wayland.desktop"
  fi
fi

DMCONF="/etc/sysconfig/displaymanager"

if [[ -f "$DMCONF" ]]; then
  if grep -q '^DISPLAYMANAGER_AUTOLOGIN=' "$DMCONF"; then
    sed -i "s|^DISPLAYMANAGER_AUTOLOGIN=.*|DISPLAYMANAGER_AUTOLOGIN=\"${USERNAME}\"|g" "$DMCONF"
  else
    printf '\nDISPLAYMANAGER_AUTOLOGIN="%s"\n' "$USERNAME" >> "$DMCONF"
  fi
else
  printf 'DISPLAYMANAGER_AUTOLOGIN="%s"\n' "$USERNAME" > "$DMCONF"
fi

ASF="/var/lib/AccountsService/users/${USERNAME}"
if [[ -f "$ASF" ]]; then
  if grep -q '^Session=' "$ASF"; then
    sed -i "s|^Session=.*|Session=default|g" "$ASF"
  else
    printf '\nSession=default\n' >> "$ASF"
  fi
else
  mkdir -p "$(dirname "$ASF")"
  printf "[User]\nSession=default\n" > "$ASF"
fi

[[ -f "$SESSION_DESKTOP" ]] && ln -sf "$SESSION_DESKTOP" /etc/alternatives/default-waylandsession.desktop
